# Generated by Django 5.2.3 on 2025-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('user', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('canceled', 'CANCELED'), ('completed', 'COMPLETED')], default='PENDING', max_length=9)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
