# Generated by Django 5.2.3 on 2025-09-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('canceled', 'CANCELED'), ('completed', 'COMPLETED')], default='pending', max_length=9),
        ),
    ]
